MISP-1266: Remove incorrect license identifiers
Ultimaker/qt5 pull request #7
Opened 2021-04-13 21:57 UTC by shanx

2021-04-14 08:07 UTC, robinmdh commented
this is open source and here the license is valid IMHO

2021-04-14 08:38 UTC, robinmdh commented
I'll make a suggestion for that change.

2021-04-14 08:40 UTC, robinmdh commented on build_for_ultimaker.sh
> -#
```suggestion
# SPDX-License-Identifier: LGPL-3.0+ 
#
```

2021-04-15 05:41 UTC, CoenSchalkwijk requested changes

2021-04-15 05:41 UTC, CoenSchalkwijk commented on build_for_ultimaker.sh
> -#
+1 
Not only that: this file is used in multiple repositories and already marked as LGPL.

2021-04-15 13:38 UTC, bryanfoley approved these changes

2021-04-16 06:00 UTC, CoenSchalkwijk approved these changes

2021-04-16 06:01 UTC, merged